# repos:
#   - repo: local
#     hooks:
#       - id: rubocop
#         name: Rubocop
#         language: system
#         entry: rubocop
#         require_serial: true # for proper cache behavior
#         files: (?x)(
#           \.rb|
#           \.rake|
#           \.gemspec|
#           \.jbuilder|
#           Gemfile|
#           Rakefile)$
#         args:
#           - --autocorrect
#           - --server
#           - --fail-level=convention
    